### ISSUE TITLE
Export position to Polaric tracking server

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/rescue-me#153] opened 2017-03-06 16:49 UTC
A valuable feature will be to have the located position easily exported with a single button-click to the Polaric tracking server (like http://tracking.nrkh.net/) as an APRS object. This will save time and prevent possible errors caused by mistyping a digit.

**Comment by svenove** [comment] 2017-03-06 20:23
Duplicate of #12.
We already thought about it, just haven't found the time to work out the specifics and implement it...

**Closed by svenove** 2017-03-06 20:23 UTC
